### ISSUE TITLE
Rank check

### ISSUE THREAD

**Issue by MineTim** [StoneMain/Shortranks#1]
Hey, at first: your plugin works very well with LuckPerms!

But I have a issue:

When I change the rank from a player, your plugin does not change the rank at the time. Later, if I reconnect, it will change the rank (or if I update the prefixes in LuckPerms). Can you fix that the plugin change the rank without reconnecting/without command?

And it is possible that you can start a spigot project and upload a .jar-file there or can you upload the .jar-file here?

Greetings
Minecraft_Tim

**Comment by mikroskeem** [comment]
Could you please turn on debug mode for plugin (from configuration) and [paste the server log](https://paste.wut.ee)?

**Comment by MinecraftTim123** [comment]
Of course, wait a minute

**Comment by MinecraftTim123** [comment]
Ahh, I found the mistake!

That mistake is only if I write /lpb user xyz parent add/remove xyz

But I want to use /lpb, because otherwise, the tablist shows not the new rang

**Comment by mikroskeem** [comment]
> Can you add a sync with /lpb please :)?

Shouldn't that be handled by LP sync functionality?

I haven't tested my plugin on network yet, because of network I'm developing this plugin for is not working yet :(

**Comment by MinecraftTim123** [comment]
Principality yes, but she tablist shows then the old rang... :/

**Comment by MinecraftTim123** [comment]
Maybe a plugin for the Bungee-session who register that command and update then the rank would be fine :/

**Comment by mikroskeem** [comment]
Try [this](https://0x0.st/kA0.jar) build.

**Comment by MinecraftTim123** [comment]
And how do I compile the plugin?

You said sth about ./grandlew build...

**Comment by mikroskeem** [comment]
Link is in my previous comment.

**Comment by MinecraftTim123** [comment]
Wait a secound

**Comment by MinecraftTim123** [comment]
No, sorry, I don't have a clue how to compile a plugin :C

**Comment by mikroskeem** [comment]
Literally there was a link to plugin jar in my comment. I'll put it here again: **[https://0x0.st/kA0.jar](https://0x0.st/kA0.jar)**

**Comment by MinecraftTim123** [comment]
![pic1](https://user-images.githubusercontent.com/26803527/28754224-95cc293e-7541-11e7-84fb-aa030500cc63.png)

Nope, does not work. Maybe you need a listener for Bungee?

**Comment by MinecraftTim123** [comment]
I think that you have to write a plugin for BungeeCord (as default) and a bridge/listener (spigot) and when sth change => change in Bungee (Tablist) and Spigot (Name)

You understand what I mean?

**Comment by mikroskeem** [comment]
Well yes I clearly understand what you mean.

I expected that LuckPerms' `PostSyncEvent` would fire when stuff is changed on BungeeCord side and eventually would reach on classical servers.. As you can see [I added listener for it](https://github.com/StoneMain/Shortranks/blob/master/src/main/kotlin/eu/mikroskeem/shortranks/hooks/LuckPermsHook.kt#L61).

I'm trying to solve this in easier ways, instead of light-handedly creating BungeeCord version of this plugin and making it communicate with backend servers; as that would kill simplicity of my plugin's code. If I'll get more time I will look into this.

**Comment by MineTim** [comment]
Ok, I understand you completely!!

Good luck! :/

**Comment by mikroskeem** [comment]
According to my testing, network sync works perfectly, just lags behind about 10 seconds (at worst).

BungeeCord log snip: https://paste.wut.ee/gisabetoto.sql  
Backend server log snip: https://paste.wut.ee/ewedodatol.sql

Make sure you have working synchronization and you will be okay.

**Comment by MineTim** [comment]
That fit!

But /lpb user xyz parent add (or remove) <group> will not change the nametag...

**Comment by mikroskeem** [comment]
That now depends on your permissions setup. Make sure your rank weights are set properly :wink:

**Comment by MineTim** [comment]
That works correctly!!

Maybe, if you want, I invite you to my server so you are able to see what I mean

**Comment by mikroskeem** [comment]
Sure.

**Comment by MineTim** [comment]
3:30pm?

IP: 91.121.64.41

**Comment by mikroskeem** [comment]
Issue solved by turning on plugin messaging in LuckPerms configuration.

**Comment by MineTim** [comment]
Thamms for helping!!
